---
title: "R Notebook"
output: html_notebook
---




# Libraries
```{r}
library(quantmod)
library(tseries)
library(timeSeries)
library(forecast)
library(xts)
library(dplyr)

library(foreach)
library(doParallel)
```

```{r}
df <- read.csv("./data/btc/btc-final.csv", sep = "\t", header = TRUE)
data <- df
data$date <- as.POSIXct(data$date)
data <- data %>% filter(date > "2015-01-27")
head(data)
```

Ran adf.test. Both close price differences and log of differences are significant and therefore stationary. close_price_returns is stationary.
found best model to be the ARIMA(4,0,5) based on auto.arima search.

```{r}
m1_arima45_dif_price_close <- arima(diff(data$price_close), order=c(4,0,5))
m2_arima45_returns <- arima(data$close_price_returns, order = c(4,0,5))
m3_arima3030 <- arima(diff(data$price_close), order=c(30,0,30))
```
```{r}
actual_series <- xts(0, as.POSIXct("2015-01-27 00:05:00","%Y-%m-%d %H:%M:%S"))
actual_series 
# Initialzing a dataframe for the forecasted return series
forecasted_series <- data.frame(Forecasted = numeric())

breakpoint <- floor(nrow(stock)*(.8))
stock.train <- 
```

```{r}
m1 <- auto.arima(stock$diff)
m2 <- auto.arima(stock$diff, max.P = 30, max.Q = 30, max.order = 60)
```

```{r}
summary(m2)
m3 <- auto.arima(stock_train, max.P = 30, max.Q = 30, max.order = 60)
```

# sliding windows

```{r}

# for (b in breakpoint:(nrow(stock)-1)) {
  cat(paste0("\rWorking on itteration: ", (b-breakpoint+1), "/", (nrow(stock)-1-breakpoint)))
  
  b <- breakpoint
  
  stock_train = stock[1:b, "diff"]
  stock_test = stock[(b+1):nrow(stock), "diff"]
  
  
  # Summary of the ARIMA model using the determined (p,d,q) parameters
  fit = ARIMA(stock_train, order = c(4, 0, 5))
  summary(fit)
  
  # plotting a acf plot of the residuals
  acf(fit$residuals,main="Residuals plot")
  
  # Forecasting the log returns
  # arima.forecast = forecast.Arima(fit, h = 1,level=99)
  arima.forecast = forecast(fit, h = 1,level=99)
  summary(arima.forecast)
  
  # plotting the forecast
  par(mfrow=c(1,1))
  plot(arima.forecast, main = "ARIMA Forecast")
  
  # Creating a series of forecasted returns for the forecasted period
  forecasted_series = rbind(forecasted_series,arima.forecast$mean[1])
  colnames(forecasted_series) = c("Forecasted")
  
  # Creating a series of actual returns for the forecasted period
  actual_return = stock[(b+1),]
  actual_series = c(Actual_series,xts(Actual_return))
  rm(actual_return)
  
  print(stock_prices[(b+1),])
  print(stock_prices[(b+2),])

# }

```



# Parallel Sliding windows
```{r}
no_cores <- detectCores() - 2 # 8 cores on server
cluster <- makeCluster(no_cores)
registerDoParallel(cluster)
```

```{r}
#Vector output
foreach(exponent = 1:5, .combine = c)  %dopar%  base^exponent
 
 
#Matrix output
foreach(exponent = 1:5, .combine = rbind)  %dopar%  base^exponent

 
#List output
foreach(exponent = 1:5, .combine = list, .multicombine=TRUE)  %dopar%  base^exponent

 
stopImplicitCluster()
```



























































